[package]
name = "rapport-temporal"
description = "Deal with time without all the fuss. Includes date, time, recurrence, and language-oriented date math."
keywords = ["date", "time", "recurrence", "calendar", "ergonomic"]
categories = ["date-and-time"]
readme = "README.md"
version = "0.2.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
chrono.workspace = true
derive_more.workspace = true
facet.workspace = true
nonempty.workspace = true
parking_lot.workspace = true
regex.workspace = true
regex-macro.workspace = true
serde.workspace = true
strum.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
claims.workspace = true
pretty_assertions.workspace = true
rstest.workspace = true
tracing-test.workspace = true

[lints]
workspace = true
