[package]
name = "rapport-files"
description = "Testable filesystem primitives for Rapport workflow code."
keywords = ["filesystem", "testing", "cli", "agent", "workflow"]
categories = ["filesystem", "development-tools::testing"]
readme = "README.md"
version = "0.2.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
camino.workspace = true

[dev-dependencies]
claims.workspace = true

[lints]
workspace = true
