[package]
name = "rapport"
description = "agent-friendly builder"
keywords = ["cli", "build", "agent", "developer-tools", "automation"]
categories = ["command-line-utilities", "development-tools::build-utils"]
readme = "README.md"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
rapport-cli = { path = "../rapport-cli", version = "0.1.0" }
rapport-prose = { path = "../rapport-prose", version = "0.1.0" }
camino.workspace = true
nonempty.workspace = true
strum.workspace = true

[dev-dependencies]
assert_cmd = "2.2"
indoc = "2.0"
insta = { version = "1.47", default-features = false, features = ["filters"] }
pretty_assertions.workspace = true
tempfile = "3.27"

[lints]
workspace = true
