[package]
name = "rapport"
description = "agent-friendly builder"
keywords = ["cli", "build", "agent", "developer-tools", "automation"]
categories = ["command-line-utilities", "development-tools::build-utils"]
readme = "README.md"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
rapport-cli = { path = "../rapport-cli" }
rapport-prose = { path = "../rapport-prose" }
strum.workspace = true

[lints]
workspace = true
