[package]
name = "rapport-cli"
description = "easily build clis that humans and agents will love"
keywords = ["clap", "cli", "command-line", "agent", "ergonomic"]
categories = ["command-line-interface", "development-tools"]
readme = "README.md"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]

[lints]
workspace = true
